#server:
#  port: 8761
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#
#spring:
#  application:
#    name: eurka-serverspring:
spring:
  application:
    name: eureka-server
  profiles:
    active: server1