#注册中心运行的端口号
server:
  port: 8762
#注册中心应用名称
#spring:
#  application:
#      name: eureka-server
#eureka.server.enableSelfPreservation:是否向注册中心注册自己
#通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
eureka:
#  server:
#      enableSelfPreservation: false
  instance:
      hostname: server2
      prefer-ip-address: false
#      ip-address: 172.193.225.185
#      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      fetch-registry: true #一定要设置为true或者不写,否则会出现unavailable-replicas
      register-with-eureka: true  #一定要设置为true或者不写,否则会出现unavailable-replicas
      service-url:
           defaultZone: http://server1:8761/eureka/
